// Fix bug reported in newsgroup:
// Tail call optimization was interfering with catching exceptions.
// The following program should print 7, but was resulting in an uncaught
// exception.
js> function g() {
  >   throw 3;
  > }
js> function f() {
  >   try {
  >     return g();
  >   } catch (e) {
  >     return 7;
  >   }
  > }
js> f()
7